// Generated by CoffeeScript 1.7.1
var incUrlSeq;

incUrlSeq = require("../lib/livecss").incUrlSeq;

describe("incUrlSeq increases the id in the url", function() {
  var url;
  url = "/foo/bar.js?v=123";
  it("adds id in to url", function() {
    return expect(incUrlSeq(url)).to.be(url.replace('.', '--1.'));
  });
  return it("increases existing id", function() {
    var url2;
    url2 = incUrlSeq(url);
    return expect(incUrlSeq(url2)).to.be(url.replace('.', '--2.'));
  });
});
