// Generated by CoffeeScript 1.7.1
(function() {
  var Renderer, coffeescript, compilers, e, less, nib, path, stylus;

  coffeescript = require("coffee-script");

  path = require("path");

  try {
    stylus = require("stylus");
  } catch (_error) {
    e = _error;
  }

  try {
    nib = require("nib");
  } catch (_error) {
    e = _error;
  }

  try {
    less = require("less");
  } catch (_error) {
    e = _error;
  }

  compilers = {
    css: {
      render: function(filename, code, cb) {
        return cb(null, code);
      }
    },
    js: {
      render: function(filename, code, cb) {
        return cb(null, code);
      }
    },
    coffee: {
      render: function(filename, code, cb) {
        try {
          return cb(null, coffeescript.compile(code));
        } catch (_error) {
          e = _error;
          return cb(e, null);
        }
      },
      targetExt: "js"
    }
  };

  if (stylus != null) {
    compilers.styl = {
      targetExt: "css",
      render: function(filename, code, cb) {
        return stylus(code).set('filename', filename).render(cb);
      }
    };
    if (nib != null) {
      Renderer = require("stylus/lib/renderer");
      compilers.styl.render = function(filename, code, cb) {
        return stylus(code).set('filename', filename).use(nib()).render(cb);
      };
    }
  }

  if (less != null) {
    compilers.less = {
      render: function(filename, code, cb) {
        return less.render(code, {
          paths: [path.dirname(filename)]
        }, cb);
      },
      targetExt: "css"
    };
  }

  module.exports = compilers;

}).call(this);
