// Generated by CoffeeScript 1.7.1
(function() {
  exports.debug = console.debug;

  exports.notice = console.log;

  exports.info = console.info;

  exports.warn = console.warn;

  exports.warning = console.warn;

  exports.error = console.error;

  exports.critical = console.error;

}).call(this);
