// Generated by CoffeeScript 1.7.1
(function() {
  var csso, error, jsp, pro, uglify;

  csso = require("csso");

  try {
    uglify = require("uglify-js");
  } catch (_error) {
    error = _error;
    console.log("no uglify", error);
    exports.jsMinify = function(code) {
      return code;
    };
    exports.jsBeautify = function(code) {
      return code;
    };
  }

  exports.cssMinify = function(code) {
    return csso.justDoIt(code);
  };

  if (uglify != null) {
    jsp = uglify.parser;
    pro = uglify.uglify;
    exports.jsMinify = function(code) {
      var ast;
      ast = jsp.parse(code);
      ast = pro.ast_mangle(ast);
      ast = pro.ast_squeeze(ast);
      return pro.gen_code(ast);
    };
    exports.jsBeautify = function(code) {
      var ast;
      ast = jsp.parse(code);
      return pro.gen_code(ast, {
        beautify: true
      });
    };
  }

}).call(this);
